/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.udesc.prog202.exercicio01.view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author uktech
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btNovaLinha = new javax.swing.JButton();
        btRemoveLinha = new javax.swing.JButton();
        btCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel4.setBackground(new java.awt.Color(235, 98, 98));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(177, 238, 140));

        jPanel1.setBackground(new java.awt.Color(245, 255, 0));
        jPanel1.setForeground(new java.awt.Color(225, 255, 0));

        btNovaLinha.setText("Nova linha");
        btNovaLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovaLinhaActionPerformed(evt);
            }
        });
        jPanel1.add(btNovaLinha);

        btRemoveLinha.setText("Remove Linha");
        btRemoveLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveLinhaActionPerformed(evt);
            }
        });
        jPanel1.add(btRemoveLinha);

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btCalcular);

        lblResultado.setText("Resultado");
        jPanel1.add(lblResultado);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produtos", "Preço", "Quantidade", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovaLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovaLinhaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        Object[] rowData = new Object[]{"Novo produto", 0, 0};
        modelo.addRow(rowData);
    }//GEN-LAST:event_btNovaLinhaActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        int totalTabela = 0;
        TableModel modelo = this.jTable1.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String produto = (String) modelo.getValueAt(i, 0);
            int valor = (Integer) modelo.getValueAt(i, 1);
            int quantidade = (Integer) modelo.getValueAt(i, 2);
            int totalLinha = valor * quantidade;
            modelo.setValueAt(totalLinha, i, 3);
            System.out.println("(" + i + ") " + produto + " -> " + valor + " * " + quantidade + " = " + totalLinha);
            totalTabela = totalTabela + totalLinha;
        }
        lblResultado.setText("Total: " + totalTabela);
    }//GEN-LAST:event_btCalcularActionPerformed

    private void btRemoveLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveLinhaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        int selectedRow = this.jTable1.getSelectedRow();
        while (selectedRow != -1) {
            modelo.removeRow(selectedRow);
            selectedRow = this.jTable1.getSelectedRow();
        }
    }//GEN-LAST:event_btRemoveLinhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btNovaLinha;
    private javax.swing.JButton btRemoveLinha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
