/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.udesc.prog202.prova01.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Carlos Alberto Cipriano Korovsky <carlos.korovsky@gmail.com>
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btNovaLinhaPedido = new javax.swing.JButton();
        btCalcularPedido = new javax.swing.JButton();
        btConfirmarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPedido = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btLimparFatura = new javax.swing.JButton();
        btFaturar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFatura = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedidos e Faturamento");
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        btNovaLinhaPedido.setText("Nova Linha Pedido");
        btNovaLinhaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovaLinhaPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btNovaLinhaPedido);

        btCalcularPedido.setText("Calcular Pedido");
        btCalcularPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btCalcularPedido);

        btConfirmarPedido.setText("Confirmar Pedido");
        btConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btConfirmarPedido);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        tbPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor Unitário", "Quantidade", "Vendido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPedido);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(153, 255, 0));

        btLimparFatura.setText("Limpar Fatura");
        btLimparFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparFaturaActionPerformed(evt);
            }
        });
        jPanel5.add(btLimparFatura);

        btFaturar.setText("Faturar");
        btFaturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFaturarActionPerformed(evt);
            }
        });
        jPanel5.add(btFaturar);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel5.add(btSair);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        tbFatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor Unitário", "Quantidade", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbFatura);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNovaLinhaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovaLinhaPedidoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.tbPedido.getModel();
        Object[] rowData = new Object[]{"Novo produto", 0, 0, Boolean.FALSE};
        modelo.addRow(rowData);
    }//GEN-LAST:event_btNovaLinhaPedidoActionPerformed

    private void btCalcularPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularPedidoActionPerformed
        int soma = 0;
        TableModel modelo = this.tbPedido.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            int valor = (Integer) modelo.getValueAt(i, 1);
            int qtde = (Integer) modelo.getValueAt(i, 2);
            soma = soma + (valor * qtde);
        }
        JOptionPane.showMessageDialog(this, "Valor total do pedido: " + soma);
    }//GEN-LAST:event_btCalcularPedidoActionPerformed

    private void btConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarPedidoActionPerformed
        limpaTabelaFatura();
        TableModel modeloPedido = this.tbPedido.getModel();
        DefaultTableModel modeloFatura = (DefaultTableModel) this.tbFatura.getModel();
        for (int i = 0; i < modeloPedido.getRowCount(); i++) {
            String produto = (String) modeloPedido.getValueAt(i, 0);
            int valor = (Integer) modeloPedido.getValueAt(i, 1);
            int qtde = (Integer) modeloPedido.getValueAt(i, 2);
            Boolean vendido = (Boolean) modeloPedido.getValueAt(i, 3);
            if (vendido == true) {
                Object[] rowData = new Object[]{produto, valor, qtde};
                modeloFatura.addRow(rowData);
            }
        }
        //if (modeloFatura.getRowCount() <= 0) {
        if (modeloFatura.getDataVector().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Nenhum item aprovado para venda",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btConfirmarPedidoActionPerformed

    private void btLimparFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparFaturaActionPerformed
        limpaTabelaFatura();
    }//GEN-LAST:event_btLimparFaturaActionPerformed

    private void btFaturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFaturarActionPerformed
        int soma = 0;
        TableModel modelo = this.tbFatura.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            int valor = (Integer) modelo.getValueAt(i, 1);
            int qtde = (Integer) modelo.getValueAt(i, 2);
            int total = (valor * qtde);
            modelo.setValueAt(total, i, 3);
            soma = soma + total;
        }
        JOptionPane.showMessageDialog(this, "Valor total da fatura: " + soma);
    }//GEN-LAST:event_btFaturarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(this, "Deseja sair?", 
                "Mensagem", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btSairActionPerformed

    private void limpaTabelaFatura() {
        DefaultTableModel modeloFatura = (DefaultTableModel) this.tbFatura.getModel();
        //modeloFatura.setRowCount(0);
        while (this.tbFatura.getRowCount() > 0) {
            modeloFatura.removeRow(0);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcularPedido;
    private javax.swing.JButton btConfirmarPedido;
    private javax.swing.JButton btFaturar;
    private javax.swing.JButton btLimparFatura;
    private javax.swing.JButton btNovaLinhaPedido;
    private javax.swing.JButton btSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbFatura;
    private javax.swing.JTable tbPedido;
    // End of variables declaration//GEN-END:variables
}
